"// Table $1  Models "
"export interface $1_Models {",
"}",
"// Model สำหรับ Get ALL",
"export interface $1_GetALL {",
  "// รายการ ฟิลด์ จาก Swagger ของ Get ALL",
"}",
"// Model สำหรับ Get By ID",
"export interface $1_ByID {",
  "// รายการ ฟิลด์ จาก Swagger ของ Get By ID",
"}",
"// Model สำหรับ Post",
"export interface $1_POST {",
 " // รายการ ฟิลด์ จาก Swagger ของ  POST",
"}",
"// Model สำหรับ PATCH",
"export interface $1_POST {",
  "// รายการ ฟิลด์ จาก Swagger ของ  POST",
"}",
"// Model สำหรับ delete",
"export interface $1_POST {",
  "// รายการ ฟิลด์ จาก Swagger ของ  POST",
"}"
